ervices:
- type: web
  name: client
  env: static
  buildCommand: yarn; cd packages/client; yarn build
  staticPublishPath: ./public
  buildFilter:
    paths:
    # build and deploy frontend if any js file under the static dir changes
    # changes to the server directory do not match this pattern
    - packages/client/**/*.?s
    - packages/client/**/*.tsx
    - packages/client/**/*.js
    - packages/client/**/*.json
- type: web
  name: server
  branch: main
  env: node
  buildCommand: cd packages/client; yarn build
  startCommand: cd packages/server; yarn start
  buildFilter:
    # build and deploy our node-server whenever any go file changes but
    # ignore any test files
    paths:
    # changes to the frontend dir do not match this pattern
    - packages/server/**/*.ts
    - packages/server/dist/**/*.js
    ignoredPaths:
    # - server/**/*_test.go